# -*- mode: python; -*-

# mathtext - A TeX/LaTeX compatible rendering library. Copyright (C)
# 2008-2012 Yue Shi Lai <ylai@users.sourceforge.net>
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA

import os

Import('env')

app_env = env.Clone()

for path in app_env['FORTRANLIBPATH']:
    app_env.Append(LIBPATH = [path])
    app_env.Append(LINKFLAGS = ['-Wl,-rpath,%s' % path])

app_env.Prepend(CPPPATH = [
    os.path.join('#', 'src', 'libgluonbase'),
    os.path.join('#', 'src', 'libmathtext'),
    os.path.join('#', 'src', 'app')])

app_env.Append(LIBPATH = [
    os.path.join('#', 'build', 'src', 'libgluonbase'),
    os.path.join('#', 'build', 'src', 'libmathtext')])

for key in ['BOOST_LIBS', 'SDL_LIBS', 'OPENGL_LIBS', 'FTGL_LIBS',
            'LCMS_LIBS', 'JPEG_LIBS', 'READLINE_LIBS']:
    if app_env.has_key(key):
        app_env.Append(LIBS = app_env[key])

library_source = []
if '-ipo' in env['CXXFLAGS']:
    library_source = env['LIBRARY_SOURCE']
else:
    app_env.Prepend(LIBS = ['gluonbase', 'mathtext'])

app_env.Program(['mathtest.cc'] + library_source)
app_env.Program(['symbol.cc'] + library_source)
